#!/usr/bin/env python3
"""Convert the header brand artwork in assets/ into main/logo.c.

Each logo becomes an 8-bit coverage mask that display_blit_alpha() blends from
the card colour toward white. Coverage is luminance x alpha so the Cursor cube
keeps its three shaded faces instead of flattening into a silhouette.

Requires Pillow; SVG sources also require CairoSVG. The output is committed, so this only needs to be re-run when
the artwork or the target heights change:

    python3 scripts/generate_logos.py
"""

from __future__ import annotations

import io
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    from PIL import Image
except ImportError:  # pragma: no cover - developer tooling only
    sys.exit("Pillow is required: python3 -m pip install Pillow")

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "main" / "logo.c"


@dataclass(frozen=True)
class Logo:
    name: str
    source: str
    # Fraction of the cropped width holding a glyph that sits on the baseline
    # without a descender or an oversized mark, used to align all logos to the
    # panel's text baseline. None means the mask is an icon with no baseline.
    baseline_cols: tuple[float, float] | None
    height: int
    invert: bool = False


# Every lockup renders at this box height so the 3.5" header footprint stays
# identical whichever app is focused. 24 px keeps the Cursor lettering legible
# without the OpenAI wordmark crowding the clock.
LOGO_HEIGHT = 24
# Round Super Mini icons sit above MODEL; 36 px leaves a gap to the label.
ICON_HEIGHT = 36

LOGOS = (
    Logo("cursor", "cursor-lockup-white.png", (0.30, 1.0), LOGO_HEIGHT),
    Logo("openai", "openai-wordmark-white.png", (0.0, 0.17), LOGO_HEIGHT),
    Logo("opencode", "opencode-wordmark-dark.svg", (0.0, 0.10), LOGO_HEIGHT),
    Logo("cursor_icon", "cursor-cube-dark.png", None, ICON_HEIGHT),
    Logo("openai_icon", "openai-blossom-white.png", None, ICON_HEIGHT),
    Logo("opencode_icon", "opencode-logo-dark.png", None, ICON_HEIGHT, invert=True),
)


def build(logo: Logo) -> tuple[Image.Image, int]:
    source = ROOT / "assets" / logo.source
    if source.suffix.lower() == ".svg":
        try:
            import cairosvg
        except ImportError:
            sys.exit("CairoSVG is required for SVG artwork: python3 -m pip install CairoSVG")
        image = Image.open(io.BytesIO(cairosvg.svg2png(url=str(source)))).convert("RGBA")
    else:
        image = Image.open(source).convert("RGBA")
    image = image.crop(image.getchannel("A").getbbox())

    luma = image.convert("L").load()
    alpha = image.getchannel("A").load()
    mask = Image.new("L", image.size)
    pixels = mask.load()
    for y in range(image.height):
        for x in range(image.width):
            coverage = luma[x, y] * alpha[x, y] // 255
            if logo.invert:
                coverage = (255 - luma[x, y]) * alpha[x, y] // 255
            pixels[x, y] = coverage

    if logo.baseline_cols is None:
        baseline = logo.height
    else:
        lo = int(round(logo.baseline_cols[0] * image.width))
        hi = int(round(logo.baseline_cols[1] * image.width))
        box = mask.crop((lo, 0, hi, image.height)).point(lambda v: 255 if v > 32 else 0).getbbox()
        if box is None:
            raise SystemExit(f"{logo.name}: baseline column range is empty")
        baseline = round(box[3] * logo.height / image.height)

    width = max(1, round(image.width * logo.height / image.height))
    return mask.resize((width, logo.height), Image.LANCZOS), baseline


def emit(handle, logo: Logo, mask: Image.Image, baseline: int) -> None:
    data = mask.tobytes()
    handle.write(f"\nstatic const uint8_t s_{logo.name}_alpha[] = {{\n")
    for offset in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[offset:offset + 16])
        handle.write(f"    {row},\n")
    handle.write("};\n\n")
    handle.write(
        f"const logo_t logo_{logo.name} = {{\n"
        f"    .width = {mask.width},\n"
        f"    .height = {mask.height},\n"
        f"    .baseline = {baseline},\n"
        f"    .alpha = s_{logo.name}_alpha,\n"
        f"}};\n"
    )


def main() -> None:
    built = [(logo, *build(logo)) for logo in LOGOS]
    with OUTPUT.open("w") as handle:
        handle.write(
            "/* Generated by scripts/generate_logos.py from assets/ -- do not edit. */\n"
            "\n"
            '#include "logo.h"\n'
        )
        for logo, mask, baseline in built:
            emit(handle, logo, mask, baseline)
    for logo, mask, baseline in built:
        print(f"{logo.name}: {mask.width}x{mask.height} baseline={baseline} "
              f"({mask.width * mask.height} bytes)")


if __name__ == "__main__":
    main()
